project:
  type: book
  output-dir: docs

book:
  title: "Rajapintojen käyttö ihmis- ja yhteiskuntatutkimuksessa"
  author: "Oliver Saal"
  date: last-modified
  chapters:
    - index.qmd
    - references.qmd
  page-navigation: true
  search: true
  repo-url: https://github.com/osaal/rajapintatutkimus
  repo-actions: [issue, source]
  sidebar:
    style: docked
    contents: auto

bibliography: references.bib

format:
  html:
    theme:
      light: flatly
      dark: darkly
